name: Lint and Format

on:
  pull_request:
    branches:
      - '**'  # Triggers on any branch

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          npm install --save-dev prettier

      - name: Lint code with Ruff
        run: |
          ruff check . --fix

      - name: Format code with Ruff
        run: |
          ruff format

      - name: Run Prettier
        run: |
          npx prettier --write .
